### ISSUE TITLE
Nether portal Issue

### ISSUE THREAD

**Issue by Armadillodude12** [FrozenOrb/HCTeams-Issues#14]
I have figured this out you are able to shot and kill faction members through nether portal with bow , would appreciate if fixed since a kid in fac has got killed before.

**Comment by jhalt** [comment]
Hi @Armadillodude12,

I'm going to verify this tonight and report back. If I can reproduce the issue, we'll classify this as a bug and get it fixed! If I can't reproduce this in my testing, I'll give you the opportunity to provide a video or other demonstration of the bug so that we can get it fixed.

I'll report back soon.

Thanks,
Jonathan

**Comment by jhalt** [comment]
We were able to reproduce this, however, due to the issue's rare and avoidable nature, we've decided that we will not be fixing this issue.
