### ISSUE TITLE
/f ignore command

### ISSUE THREAD

**Issue by Strafin** [FrozenOrb/HCTeams-Issues#16]
Only members can /f ignore. Make it so /f ignore is only for the leader and captains. Also make it so you can do /f unignore then tab complete and it will list the factions you have ignored.

**Comment by BizarreAlex** [comment]
There is also a grammatical error in the message sent when a team is un-ignored.
![Error](https://i.gyazo.com/45c3b489b5435fae8f95f5dff3c9f982.png)

**Comment by jhalt** [comment]
@Strafin: We will end up re-implementing this properly so that faction ignores are on a per-player basis. (The function where a faction leader/captain can ignore an entire other faction for another player is a potato).

@BizarreAlex: I've gone ahead and fixed the grammatical error. Thanks.

**Comment by jhalt** [comment]
We added a temporary workaround so that this authority is given back to leaders instead of members in https://github.com/FrozenOrb/HCTeams/commit/42115faa9367d57b86e7b1359aad6afec81b1520. We'll update this issue when this command is fully fixed and done the way it was supposed to be (a per-user, individual setting).
