### ISSUE TITLE
"/leavequeue" confirmation message missing character 

### ISSUE THREAD

**Issue by BizarreAlex** [FrozenOrb/HCTeams-Issues#17]
Not necessarily an "HCTeams" or "HCSquads" issue, but upon typing "/leavequeue" in the hub the message sent as confirmation is missing a space.

![Image of error](https://i.gyazo.com/c80c61f47b5068a3380823cdc41d1c02.png)

**Comment by jhalt** [comment]
This was resolved in https://github.com/FrozenOrb/BungeeQueues/commit/3c309a54d7b2ec0c16e8a0fe4941ff7de2f492c8. We have not yet deployed this version to production, however.

Because this issue does not affect HCTeams directly and is a minor cosmetic issue that is fixed in the next deployment, I'm going to close this issue.
